### ISSUE TITLE
Some jobs are forever in 'Running' State with WorkflowTaskFailed Error 

### ISSUE THREAD

**Issue by gosandhya** [temporalio/sdk-java#744] opened 2021-09-21 08:20 UTC
Some of the workflows remain in Running state while WorkFlowTask failed activity is triggered with the following error. This seems to happen only when I trigger multiple (20-100) instances of the workflow at the same time so it is a little sporadic in nature. The same workflow that works normally, hangs in ‘running’ mode with the error below:

## Expected Behavior
All runs finish with 'complete' status 

## Actual Behavior
Some runs fail with the following bug

```
15:25:20.731 [Workflow Executor taskQueue="Classify", namespace="default": 1568] ERROR i.t.internal.worker.PollerOptions - uncaught exception
java.lang.RuntimeException: Failure processing workflow task. WorkflowId=438cb389-3973-49cf-b298-64cee904ad44, RunId=6810e3eb-be56-4e3b-b810-3c12bf44f76e, Attempt=798
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:349)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:279)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:79)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.temporal.internal.replay.InternalWorkflowTaskException: Failure handling event 302 of 'EVENT_TYPE_WORKFLOW_TASK_STARTED' type. IsReplaying=false, PreviousStartedEventId=302, workflowTaskStartedEventId=302, Currently Processing StartedEventId=302
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:188)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleEvent(ReplayWorkflowRunTaskHandler.java:140)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:180)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:150)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithEmbeddedQuery(ReplayWorkflowTaskHandler.java:201)
	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:114)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:319)
	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:279)
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
	... 3 common frames omitted
Caused by: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED]
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:140)
	at io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:91)
	at io.temporal.internal.statemachines.EntityStateMachineBase.handleEvent(EntityStateMachineBase.java:63)
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEventImpl(WorkflowStateMachines.java:205)
	at io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:173)
	... 11 common frames omitted
Caused by: java.lang.ClassCastException: class scala.runtime.NonLocalReturnControl cannot be cast to class java.lang.Exception (scala.runtime.NonLocalReturnControl is in unnamed module of loader 'app'; java.lang.Exception is in module java.base of loader 'bootstrap')
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:56)
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:412)
	at io.temporal.internal.sync.DeterministicRunnerImpl.runUntilAllBlocked(DeterministicRunnerImpl.java:211)
	at io.temporal.internal.sync.SyncWorkflow.eventLoop(SyncWorkflow.java:148)
	at io.temporal.internal.replay.ReplayWorkflowExecutor.eventLoop(ReplayWorkflowExecutor.java:74)
	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler$EntityManagerListenerImpl.eventLoop(ReplayWorkflowRunTaskHandler.java:329)
	at io.temporal.internal.statemachines.WorkflowStateMachines.eventLoop(WorkflowStateMachines.java:400)
	at io.temporal.internal.statemachines.WorkflowStateMachines.access$500(WorkflowStateMachines.java:71)
	at io.temporal.internal.statemachines.WorkflowStateMachines$WorkflowTaskCommandsListener.workflowTaskStarted(WorkflowStateMachines.java:820)
	at io.temporal.internal.statemachines.WorkflowTaskStateMachine.handleCompleted(WorkflowTaskStateMachine.java:121)
	at io.temporal.internal.statemachines.WorkflowTaskStateMachine.handleStarted(WorkflowTaskStateMachine.java:113)
	at io.temporal.internal.statemachines.FixedTransitionAction.apply(FixedTransitionAction.java:45)
	at io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:137)
	... 15 common frames omitted
```

## Steps to Reproduce the Problem

  1. kick-off 20-100 jobs of a custom workflow
  2. Most of them would complete successfully while few (1-9) would be in forever running state with workflowTaskFailed Activity
  

## Specifications

  - Version: Temporal Client SDK version 1.3.1
  - Platform: IntelliJ

**Comment by Spikhalskiy** [comment] 2021-09-21 20:42
Hi @gosandhya 

> Failure handling event 302 of 'EVENT_TYPE_WORKFLOW_TASK_STARTED'
It looks like we at least have workflows with some pretty long histories here.

Any chance you can provide some isolation or reproduction of the problem?
If you can't, maybe you can provide some additional details or characteristics about the type of workflows you run.

**Comment by gosandhya** [comment] 2021-09-22 08:28
Hello @Spikhalskiy 

We run a classification workflow that has multiple activities that perform fetching the data, disk operations, and finally interacting with various APIs to get back the results.

Maxim pointed out there might be an edge case unhandled in temporal Java SDK particularly NonLocalReturnControl exception extending Throwable directly in Scala which is not ideal. So was hoping this issue could be fixed.

```
Caused by: java.lang.ClassCastException: class scala.runtime.NonLocalReturnControl cannot be cast to class java.lang.Exception (scala.runtime.NonLocalReturnControl is in unnamed module of loader 'app'; java.lang.Exception is in module java.base of loader 'bootstrap')
	at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:56)
	at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:412)
```

**Comment by Spikhalskiy** [comment] 2021-09-22 23:55
Class cast exception will be fixed in 1.4.0, but the behavior itself (workflow stuck in Running) will not change.

Temporal treats only subclasses of TemporalFailure as workflow execution failure, other exceptions or throwables are treated like workflow bugs, and Temporal continues to retry them.
In your case workflows are not stuck, Temporal actually keeps retrying them and they will succeed if you fix the exception and redeploy the workers.
If you want the `scala.runtime.NonLocalReturnControl` Throwable be treated as a workflow execution failure, wrap it into TemporalFailure class or use WorkflowImplementationOptions#setFailWorkflowExceptionTypes https://github.com/temporalio/sdk-java/blob/657a392333e6d623fda91b1d7a0ea1f152f2eb9b/temporal-sdk/src/main/java/io/temporal/worker/WorkflowImplementationOptions.java#L68 to specify `scala.runtime.NonLocalReturnControl ` as a type that causes Workflow fail.

**Closed** 2021-09-23 16:50 UTC
Labels: bug

**Comment by gosandhya** [comment] 2021-09-26 18:34
Hi, thank you for responding to this promptly! Appreciate it.

Do you have any time estimate for when will version 1.4.0 be released?

**Comment by Spikhalskiy** [comment] 2021-09-26 23:38
We are currently targeting 5 October, but it's normal for us to delay releases if we are unsure about safety.
