### ISSUE TITLE
Error while implementing Inheritance | Java SDK

### ISSUE THREAD

**Issue by jeenadeepak** [temporalio/sdk-java#1551] opened 2022-12-01 04:06 UTC
class P2PProcessRequest {}
class IMPSProcessRequest {}

interface TranslationWorkflow<R> {
	void process(R request);
}

interface P2PWorkflow extends TranslationWorkflow <P2PProcessRequest>{
    @Override
    @WorkflowMethod(name = "P2P")
    void process(P2PProcessRequest request);
    
}
interface IMPSWorkflow extends OrderWorkflow <IMPSProcessRequest>{
    @Override
    @WorkflowMethod(name = "IMPS")
    void process(IMPSProcessRequest request);
    
}
class P2PWorkflowImpl implements P2PWorkflow {
    @Override
    public void process(P2PProcessRequest request) {
    	System.out.println("P2P transation done");
    }
}
class IMPSWorkflowImpl implements IMPSWorkflow {
    @Override
    public void process(IMPSProcessRequest request) {
    	System.out.println("IMPS transation done");
    }
}

I am trying to implement 2 different flow for transition.

## Expected Behavior
Code should execute successfully for above show scenario.

## Actual Behaviour
Thowing error multiple signal method found P2PWorkflow:process and TranslationWorkflow:process, while creating P2PWorkflow/IMPSWorkflow workflow stub.
 @WorkflowMethod is only define one time for TranslationWorkflow.

  - Version: v1.17.0
  - Platform: java

**Comment by mfateev** [comment] 2022-12-08 00:14
Generics are not supported. What is the R type?

**Comment by Spikhalskiy** [comment] 2022-12-08 00:33
Duplicate of #1106

**Closed by Spikhalskiy** 2022-12-08 00:33 UTC
