### ISSUE TITLE
Issue with ReplayAwareLogger and CanceledFailure

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1558] opened 2022-12-05 22:12 UTC
When catching ActivityFailure with cause io.temporal.failure.CanceledFailure it seems ReplayAwareLogger thinks workflow is in replay mode, looks like issue with setting WorkflowUnsafe.isReplaying() in this case. 

Full repro (could run in within java samples) [here](https://gist.github.com/tsurdilo/4eb48c5f87fe8797b4a7a4399375ee85). 
Relevant lines where issue happens (only system outs get printed) [here](https://gist.github.com/tsurdilo/4eb48c5f87fe8797b4a7a4399375ee85#file-gistfile1-txt-L77-L82).

**Comment by dano** [comment] 2023-03-02 17:16
I want to add that this issue actually does more than just screw up `ReplayAwareLogger`. If you try to use a `mutableSideEffect` in a detached `CancellationScope` when the Workflow mistakenly thinks it is replaying, when it is actually just cancelled, the `mutableSideEffect` call will fail with this error:
```
023-03-02 12:10:23.856 [WARN ] [io.temporal.internal.worker.WorkflowWorker|Workflow Executor taskQueue="myQueue", namespace="default": 2] Failure while reporting workflow progress to the server. If seen continuously the workflow might be stuck. WorkflowId=799e5987-65a9-4c1d-bd4e-bc96301ae825, RunId=839fbc5c-9c5c-4a7d-be4d-085b296bc883, startedEventId=19
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: BadRecordMarkerAttributes: MarkerName is not set on command.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.48.1.jar:1.48.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.48.1.jar:1.48.1]
```

You can reproduce it by taking @tsurdilo's original gist, and replaying the call inside the `CancellationScope` on line 71 with a `Workflow.mutableSideEffect` call. It looks like the `MutableSideEffectStateMachine` ends up sending a "fake" `RecordMarkerCommandAttrivutes` instance to the server because it thinks it's replaying.

It's possible that other behavior will be broken by this as well.

**Comment by dano** [comment] 2023-03-02 18:54
It seems like something about the `ActivityTaskCanceled` event screws up the logic `WorkflowStateMachines` uses to determine if we're replaying. We end up making progress executing the Workflow while it still thinks it should be replaying the event history.

**Comment by dano** [comment] 2023-03-06 23:06
Ok, I've figured out the root cause for the bad behavior. It's because of this logic in `WorkflowStateMachines.scheduleActivityTask`:

``` java
              callback.apply(p, f);
              if (f != null && f.hasCause() && f.getCause().hasCanceledFailureInfo()) {
                eventLoop();
              }
```
When that `if` statement evaluates to true (meaning the activity has thrown a `CanceledFailure`), and the event loop is allowed to run, it causes the Workflow to make progress while it is still in the replaying state, which causes all the bad behavior reported in this issue. With any non-cancellation failure, the event loop doesn't run until all events in the event history get processed (specifically the `WorkflowTaskScheduled` and `WorkflowTaskStarted` events that are waiting behind the `ActivityTaskFailed`/`ActivityTaskCanceled` event, which sets replaying back to `false` inside `WorkflowStateMachines.handleSingleEvent`).

It looks like this code has been there for several years, though, so I imagine it is there for a reason. I will experiment with code changes tomorrow to see if I can find one that fixes the issue I'm seeing, without breaking any tests, but probably I will need @Spikhalskiy to weigh in here.

**Comment by Spikhalskiy** [comment] 2023-03-07 03:57
@dano Thanks for your thoughts. I see what you are saying, but I don't have immediate thoughts right now how it should be fixed. State machines are not trivial to reason about without some digging. If you can provide a unit test reproducing your specific problem, it will be helpful.

**Comment by Spikhalskiy** [comment] 2023-03-07 04:01
Issue #871 is caused by the same triggering of the event loop as discussed above. The design of the fix for the current issue should be tackled keeping in mind issue #871 and it probably should address both issues at once.

**Closed** 2023-03-16 04:01 UTC
Labels: epic bug
