### ISSUE TITLE
JSON de-serializer fails on field additions and removals

### ISSUE THREAD

**Issue by ranand-git** [temporalio/sdk-java#328] opened 2021-02-01 18:47 UTC
## Expected Behavior
The Data class input parameter to a Workflow method could be changed in the following ways as part of a new deployment/rollout:
- remove an existing field in the input parameter class definition and/or
- add a new field and/or
- modify the type (and/or name) of a field. 

Note that it could be a combination of the above as well.

Temporal needs to ensure that the old workers running the old version of the code don't break. Ideally, nothing should break.

## Actual Behavior
The observed behavior is that when say a new field is added, the old worker code fails during de-serialization because of the additional fields added.

Are we **expected** to annotate our data classes with: "@JsonIgnoreProperties(ignoreUnknown = true)" before we rollout a breaking change?

I haven't tried to repro what happens when a field is removed or when the data type and/or name of a field is changed. Perhaps we need to use custom de-serializators for the latter.

All of this should be well documented. Currently, all that is documented is Temporal versioning which kicks in only after de-serialization has happened. While Temporal versioning is good for branching code when the behavior is drastically different, there is a gap on how to handle data class changes.

Note that this issue exists even for activities (when the input/output classes they use change). However, it is a blocker for data class changes for workflow methods. The fundamental question is it **even possible** to iterate on data classes used in Workflow methods or is that a sailed ship?

## Steps to Reproduce the Problem

  1. Change the data class input to a Workflow or activity by adding, removing and changing some fields and deploy this change to a running system. Ideally, test addition, removal and change separately to correctly observe the behavior.
  2. Rollout this change.
  3. The old workers running the old code will barf when they try to de-serialize the data input serialized by the new code.

## Specifications

  - Version: 1.0.3
  - Platform: Java SDK

**Comment by Spikhalskiy** [comment] 2021-09-28 15:45
Temporal doesn't handle the serialization of inputs/outputs in its code.
By default Temporal uses Jackson in it's data converters and this behavior is defined by Jackson mapper configuration.
You can set your own data converter with your own settings, for example ignoring newly added fields.
We use pretty much an [original mapper](https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-sdk/src/main/java/io/temporal/common/converter/JacksonJsonPayloadConverter.java#L40) to give users the default behavior they get used to.

I don't think that Temporal documentation should have the details of how to make changes in data classes that are compatible with **Jackson** or any other serialization framework that may be used.


We will consider adding information about default out-of-the-box serializers we supply in data converters.
We will make sure to express an idea "You should be aware of the serializer that you use and its configuration and make changes to data classes that are compatible with your combination of serializer and options if you want to maintain compatibility".

Closing the issue for being not a bug and more of misconfiguration.
The steps should be to improve Temporal documentation in this area.

**Closed by Spikhalskiy** 2021-09-28 15:45 UTC
Labels: potential bug
