### ISSUE TITLE
Test server generates the same activity task token on retry

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-java#1223] opened 2022-05-17 22:05 UTC
## Expected Behavior

Should be a different task token

## Actual Behavior

Same token issued

## Steps to Reproduce the Problem

  1. Create a test with an activity that times out
  1. Wait for second attempt
  1. Observe the issued task token

**Comment by Spikhalskiy** [comment] 2022-05-17 23:19
Duplicate of #84

**Closed by Spikhalskiy** 2022-05-17 23:19 UTC
Labels: bug
