### ISSUE TITLE
TestEnv: WorkflowStub.getResult seems to skip timer 

### ISSUE THREAD

**Issue by rubyhfu** [temporalio/sdk-java#578] opened 2021-07-07 03:55 UTC
## Expected Behavior
workflowStub.getResult should be waiting for workflow to complete synchronously and shouldn't skip timer without using testEnv.sleep()

## Actual Behavior
Skips timer and returns result immediately

## Steps to Reproduce the Problem

  1. WorkflowInterface

```
import io.temporal.workflow.SignalMethod;
import io.temporal.workflow.WorkflowInterface;
import io.temporal.workflow.WorkflowMethod;

@WorkflowInterface
public interface ExampleWorkflow {

    @WorkflowMethod
    public String execute(String s);

    @SignalMethod
    public void signal(boolean s);
}

```
  2. WorkflowImpl1
 
```
import java.time.Duration;
import io.temporal.workflow.Workflow;

public class ExampleWorkflowImpl implements ExampleWorkflow{
    private boolean signal = false;

    @Override
    public String execute(String s) {
        Workflow.await(Duration.ofMinutes(5L), () -> signal);
        Workflow.sleep(Duration.ofMinutes(10L));
        return s;
    }

    @Override
    public void signal(boolean signal) {
        this.signal = signal;
    }
}
```
  3. Run third test in test class
 
```
public class ExampleWorkflowImplTest {
    private TestWorkflowEnvironment testEnv;
    private Worker worker1, worker2;
    private WorkflowClient client;

    @BeforeEach
    public void setUp() {
        testEnv = TestWorkflowEnvironment.newInstance();
        worker1 = testEnv.newWorker("TEST_QUEUE1");
        worker2 = testEnv.newWorker("TEST_QUEUE2");
        worker1.registerWorkflowImplementationTypes(ExampleWorkflowImpl.class);
        worker2.registerWorkflowImplementationTypes(ExampleWorkflow2Impl.class);
        client = testEnv.getWorkflowClient();
        testEnv.start();
    }

    @Test
    public void testTerminateWorkflowSignalError() {
        ExampleWorkflow workflow1 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setWorkflowId("abc123")
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        ExampleWorkflow workflow2 = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE2")
                        .build());

        WorkflowExecution workflow1Execution = WorkflowClient.start(workflow1::execute, "test");

        testEnv.sleep(Duration.ofMinutes(6L));

        WorkflowExecution workflow2Execution = WorkflowClient.start(workflow2::execute, "test");
        WorkflowStub workflowStub1 = WorkflowStub.fromTyped(workflow1);
        workflowStub1.terminate("Mock terminating workflow");

        WorkflowStub workflowStub2 = WorkflowStub.fromTyped(workflow2);
        workflowStub2.getResult(String.class);
    }

    @Test
    public void testSetWorkflowExecutionTimeoutHangs() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        // setting this makes the test hang... this normally works outside of TestWorkflowEnv
                        .setWorkflowExecutionTimeout(Duration.ofSeconds(10))
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        // workflow execution timeout seems to clash with testEnv.sleep
        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
    }

    @Test
    public void testTestEnvSecondTimerSkipped() {
        ExampleWorkflow workflow = client.newWorkflowStub(
                ExampleWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("TEST_QUEUE1")
                        .build());

        WorkflowExecution workflowExecution = WorkflowClient.start(workflow::execute, "test");

        testEnv.sleep(Duration.ofMinutes(5L));

        WorkflowStub workflowStub = WorkflowStub.fromTyped(workflow);
        String result = workflowStub.getResult(String.class);
        // why is this able to get past 2nd 10min-timer immediately without moving testEnv time further?
        System.out.println(result);
    }
}

```
## Specifications

  - Version: sdk 1.0.0, junit 5
  - Platform: MacOS BigSur

**Comment by vkoby** [comment] 2021-07-07 20:39
Hi @rubyhfu ,
For clarity, you're probably using sdk 1.1.0, not 1.0.0 right?

**Comment by rubyhfu** [comment] 2021-07-07 21:52
we are stuck using 1.0.0 due to some dependencies issue right now.... let me know if you don't see these reported issues in newer version. thanks!

**Comment by vkoby** [comment] 2021-07-09 19:50
@rubyhfu, this test is passing for me with the current version. 
I'm still working on your other issues.

**Comment by Spikhalskiy** [comment] 2021-07-19 04:45
This is actually not a bug, but a feature. It's implemented in `TimeLockingInterceptor` that is used by default in the test environment: https://github.com/temporalio/sdk-java/blob/a25cafa5d363342e77af9cb4719ad7dce4dbfe43/temporal-testing/src/main/java/io/temporal/testing/TestWorkflowEnvironmentInternal.java#L304
We trigger unlimited time skipping after `getResult` is called and disable it after the workflow result is ready to be returned.
This is done to remove frustration from unit tests writers. When a unit test triggers getResult, we think that test authors are not interested in waiting for time to pass at a regular pace.
I close this issue right now because it's not a bug. But I assume that there could be some type of tests we didn't think of that this feature makes trickier to implement than it should be. Please feel free to reopen if you see a reason why this behavior should be made optional and you can elaborate. Also, feel free to ping me on Slack to discuss.

**Closed** 2021-07-19 04:49 UTC
Labels: not a bug
