### ISSUE TITLE
Default MDC entries not propagated to LocalActivities

### ISSUE THREAD

**Issue by ravikrn13** [temporalio/sdk-java#599] opened 2021-07-22 17:21 UTC
## Expected Behavior
WorkflowId, RunId etc should be propagated to LocalActivities. 

## Actual Behavior
MDC entries like WorkflowId, RunId etc are not propagated to LocalActivities. These entries are absent.
This [section](https://github.com/temporalio/sdk-java/blob/b0199150b69bb5a4eaf6c13ba4b89c2a8746a113/temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java#L182) from ActivityWorker is not present in LocalActivityWorker [handle](https://github.com/temporalio/sdk-java/blob/b23edac35fc6ef4fe44685f9897027f9d1d5569e/temporal-sdk/src/main/java/io/temporal/internal/worker/LocalActivityWorker.java#L200) method

From the thread: https://community.temporal.io/t/mdc-values-not-present-for-local-activities/2502/4

## Steps to Reproduce the Problem

  1. Create a Workflow.
  2. Create a LocalActivity.
  3. Invoke local activity from workflow.
  4. Inside local activity print `MDC.get(LoggerTag.WORKFLOW_ID) ` . 

## Specifications

  - Version: 1.0.9
  - Platform: java-sdk

**Comment by Spikhalskiy** [comment] 2021-07-22 17:56
This a duplicate of https://github.com/temporalio/sdk-java/issues/489 and it's fixed. We also have a unit test checking MDC propagation + local activities: https://github.com/temporalio/sdk-java/commit/b23edac35fc6ef4fe44685f9897027f9d1d5569e#diff-061e39ce33d4eacc5c8d5a281e5497251fa53188779217af391d87c363e4c918R1107

Please feel free to reopen this issue with a test or code demonstrating a problem.

**Closed by Spikhalskiy** 2021-07-22 17:56 UTC
Labels: potential-bug
