### ISSUE TITLE
Improve signalWithStart usability

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#915] opened 2021-12-04 23:07 UTC
`Workflow#signalWithStart` method interface is overcomplicated and hard to use without checking with samples first.
We should improve the classes structure and provide more conventional builders and factory methods around this method and functionality.

**Comment by mfateev** [comment] 2022-01-23 21:57
Such refactoring should keep the strongly typed way to call this method the current implementation provides.

**Comment by tsurdilo** [comment] 2022-02-11 18:42
Wanted to add one possible improvement. 
Currently to signalWithStart we can do for example:

    WorkflowStub untyped = WorkflowStub.fromTyped(typedStub);
    untyped.signalWithStart(...);

( or just create an untyped stub to start with ) so this works off just WorkflowStub (untyped)

WorkflowClient.signalWithStart only works off typed stubs, for example:

     BatchRequest request = client.newSignalWithStartRequest();
     request.add(myWorkflowStub::exec, input); // exec is workflow method
     request.add(myWorkflowStub::handleSignal, signalData); // handleSignal is a signal method
     client.signalWithStart(request);

It would be nice to add an "untyped" option for WorkflowClient.signalWithStart that takes in signalName, signalData, inputData.

**Comment by Quinn-With-Two-Ns** [comment] 2024-12-23 10:21
Closing as a duplicate of https://github.com/temporalio/sdk-java/issues/2213

**Closed by Quinn-With-Two-Ns** 2024-12-23 10:21 UTC
Labels: enhancement, good first issue
