### ISSUE TITLE
Support dynamic values for custom tags in metrics.

### ISSUE THREAD

**Issue by ravikrn13** [temporalio/sdk-java#1195] opened 2022-05-09 19:06 UTC
**Is your feature request related to a problem? Please describe.**
Currently custom tag values are static in nature, once set cannot be updated during the workflow execution. 
E.g: the temporal_workflow_endtoend_latency_seconds is a very useful metric, but when we share the workflow with different inputs, we would like to add a custom tag and set its value based on the input.

**Describe the solution you'd like**
Ability to modify the custom tag using Workflow.getMetricsScope().tagged() method (similarly for Activity too).

**Describe alternatives you've considered**
Alternatives are to create custom metrics similar to already exposed by SDK. 

**Additional context**
As per discussion here, https://community.temporal.io/t/update-custom-tag-value-of-built-in-metrics/4631/1

**Comment by Spikhalskiy** [comment] 2022-05-09 19:07
Duplicate of https://github.com/temporalio/sdk-java/issues/1163

Won't fix.

**Closed by Spikhalskiy** 2022-05-09 19:07 UTC
Labels: enhancement
