### ISSUE TITLE
TestActivityEnvironment: calling "close" in test method fails tests

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1133] opened 2022-04-11 14:19 UTC
To reproduce:
ActivityOptionsTest: https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/test/java/io/temporal/activity/ActivityOptionsTest.java

Add "testEnv.close()" at the end of each test method. The test env should be recreated in the "@Before" method but instead
this throws:

                java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@590c73d3 rejected from java.util.concurrent.ThreadPoolExecutor@6b9ce1bf[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
      io.temporal.internal.sync.WorkflowRejectedExecutionError: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@590c73d3 rejected from java.util.concurrent.ThreadPoolExecutor@6b9ce1bf[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	      at io.temporal.internal.sync.WorkflowThreadImpl.start(WorkflowThreadImpl.java:266)
	      at io.temporal.internal.sync.DeterministicRunnerImpl.runUntilAllBlocked(DeterministicRunnerImpl.java:160)
	      at io.temporal.internal.sync.DeterministicRunnerWrapper.invoke(DeterministicRunnerWrapper.java:53)
	      at com.sun.proxy.$Proxy13.activity1(Unknown Source)
	      at io.temporal.activity.ActivityOptionsTest.testActivityOptionsDefaultInstance(ActivityOptionsTest.java:95)
	      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.lang.reflect.Method.invoke(Method.java:498)
	      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	      at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	      at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	      at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	      at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	      at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	      at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	      at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	      at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	      at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	      at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	      at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.lang.reflect.Method.invoke(Method.java:498)
	      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	      at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	      at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	      at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	      at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	      at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	      at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	      at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	      at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	      at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	      at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	      at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	      at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	      at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
      Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@590c73d3 rejected from java.util.concurrent.ThreadPoolExecutor@6b9ce1bf[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	      at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	      at io.temporal.internal.sync.WorkflowThreadImpl.start(WorkflowThreadImpl.java:250)
	      ... 48 more

**Comment by Spikhalskiy** [comment] 2022-04-13 22:03
Likely related: https://github.com/temporalio/sdk-java/issues/928

**Comment by Bennett-Lynch** [comment] 2022-07-27 04:36
Any update?

**Comment by Spikhalskiy** [comment] 2022-07-27 04:37
The issue will be closed if the problem is resolved.
Contributions are welcomed.

**Comment by Bennett-Lynch** [comment] 2022-07-27 17:38
The root cause appears to be a static `ExecutorService activityWorkerExecutor` that is used for all `TestActivityEnvironmentInternal` instances, where a new `TestActivityEnvironmentInternal` instance is created for each test method, and the static executor is closed as part of each test method as well:

## beforeEach

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityExtension.java#L145-L148

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironment.java#L66-L68

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java#L79-L80

## during

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java#L322-L325

## afterEach

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityExtension.java#L154-L158

https://github.com/temporalio/sdk-java/blob/ae5fb81293a62f2d9c83f53d57fb1ab683713da1/temporal-testing/src/main/java/io/temporal/testing/TestActivityEnvironmentInternal.java#L239-L242

The same appears to be true for `heartbeatExecutor` and `deterministicRunnerExecutor` as well.

## Possible fixes:
1. Make these fields not static (creating a new thread pool per test may be sub-optimal for performance but is probably acceptable for most testing use cases)
2. Do not close these static fields as part of `AfterEachCallback` and instead use something like `TestExecutionListener#testPlanExecutionFinished` or a shutdown hook

**Comment by Spikhalskiy** [comment] 2022-07-27 17:56
Thank you for giving the detailed root cause analysis, much appreciated!

> Make these fields not static (creating a new thread pool per test may be sub-optimal for performance but is probably acceptable for most testing use cases)

Is the cleanest approach. #close of an instance shouldn't be closing static member as the instance creation or initialization didn't cause their creation in the first place. Let's make everything that is needed by TestActivityEnvironmentInternal and that needs a lifecycle management non-static: `heartbeatExecutor`, `activityWorkerExecutor`, `deterministicRunnerExecutor`

Will you be interested in making a PR?

**Comment by Spikhalskiy** [comment] 2022-08-04 20:46
Closed by #1329

**Closed by Spikhalskiy** 2022-08-04 20:46 UTC
Labels: bug
