### ISSUE TITLE
Support robfig style cron defs in TestWorkflowEnvironment

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1293] opened 2022-06-29 21:33 UTC
Users can set cron schedules in their WorkflowOptions using [robfig](https://pkg.go.dev/github.com/robfig/cron) schedules/intervals format, but they cannot currently use them in tests as only crontab style is supported.

This is a feature request to add support for robfig predefined schedules and intervals: https://docs.temporal.io/workflows/#robfig-predefined-schedules-and-intervals
in TestWorkflowEnvironment.

**Comment by Spikhalskiy** [comment] 2022-06-29 21:37
Duplicate of https://github.com/temporalio/sdk-java/issues/341

**Closed by Spikhalskiy** 2022-06-29 21:37 UTC
Labels: enhancement
