### ISSUE TITLE
Child workflow signal / cancellation should not use run ID

### ISSUE THREAD

**Issue by wxing1292** [temporalio/sdk-java#501] opened 2021-05-19 00:36 UTC
Existing behavior:
When signal / cancel child workflow, `RunId` is set, `ChildWorkflowOnly` is set to false

Correct behavior:
Signal / cancel child workflow should be `RunId` not set, `ChildWorkflowOnly` is set to true

Reasoning:
What if child workflow does continue as new, or child workflow is reseted.

**Comment by vitarb** [comment] 2021-06-07 17:17
We should also verify that his is not an issue in Go SDK before closing.

**Comment by vkoby** [comment] 2021-06-16 18:39
Per conversation with @wxing1292 this is hard to reproduce because the bug happens when the timing is just right. For example:
t = 0 child workflow finish
t = 1 child workflow has not report to parent yet (there can be few hundreds ms delay)
t = 2 since child workflow finished, some random guy start a workflow reusing the child workflow’s workflow ID
t = 3 parent try to cancel child, sending command with workflow ID set, run ID not set, child only == false
t = 4  some random guy’s workflow is request cancelled, since child only == false
…
After discussing with @wxing1292 and @vitarb the consensus is to implement the fix without testing. We will ensure that the existing tests pass to make sure that there are no regressions.

**Closed** 2021-06-21 16:54 UTC
Labels: potential-bug
