### ISSUE TITLE
Please add ActivityCompletionClient support in TestActivityEnvironment

### ISSUE THREAD

**Issue by wxing1292** [temporalio/sdk-java#460] opened 2021-02-11 01:11 UTC
See issue created on server side: https://github.com/temporalio/temporal/issues/1185

**Comment by CalPeterWu** [comment] 2021-06-25 20:47
Hi Temporal Team, any update on this issue? Thanks!

**Comment by Quinn-With-Two-Ns** [comment] 2024-12-23 20:08
Duplicate of https://github.com/temporalio/sdk-java/issues/2097

**Closed by Quinn-With-Two-Ns** 2024-12-23 20:08 UTC
Labels: enhancement
