### ISSUE TITLE
Workflow-init support

### ISSUE THREAD

**Issue by drewhoskins-temporal** [temporalio/sdk-java#2166] opened 2024-08-02 04:06 UTC
We should have a method that's guaranteed to initialize before signals and updates come in so handlers can use initialized values.

**Comment by Quinn-With-Two-Ns** [comment] 2024-08-06 17:16
Duplicate of https://github.com/temporalio/sdk-java/issues/865

**Closed by Quinn-With-Two-Ns** 2024-08-06 17:16 UTC
