### ISSUE TITLE
Rework HeartbeatContext to use GrpcRetryer with exponential backoff for network issues

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#947] opened 2022-01-03 17:41 UTC
## Expected Behavior
HeartbeatContext should have an exponential backoff in case of network issues

## Actual Behavior
HeartbeatContext uses a constant delay in case of network issues

**Comment by Spikhalskiy** [comment] 2023-04-20 18:06
Subtask (duplicate?) of #1258

**Comment by Quinn-With-Two-Ns** [comment] 2024-12-23 10:00
Marking as duplicate of https://github.com/temporalio/sdk-java/issues/1258

**Closed by Quinn-With-Two-Ns** 2024-12-23 10:00 UTC
Labels: enhancement, good first issue
